import { readAllProfiles } from './browsers/index.js';
import type { Bundle, Cookie, CookieSelector, SourcedCookie } from './types.js';

export const bareDomain = (domain: string): string => domain.replace(/^\./, '').toLowerCase();

/** True when `host` is the selector domain or a subdomain of it. */
export function domainCovers(selectorDomain: string, cookieDomain: string): boolean {
  const target = bareDomain(selectorDomain);
  const host = bareDomain(cookieDomain);
  return host === target || host.endsWith(`.${target}`);
}

/** Cookie-spec host matching: `.example.com` cookies are sent to subdomains. */
export function cookieAppliesToHost(cookie: Cookie, host: string): boolean {
  const cookieHost = bareDomain(cookie.domain);
  const target = host.toLowerCase();
  if (cookie.domain.startsWith('.')) return target === cookieHost || target.endsWith(`.${cookieHost}`);
  return target === cookieHost;
}

export function cookieAppliesToPath(cookie: Cookie, pathname: string): boolean {
  const cookiePath = cookie.path || '/';
  if (cookiePath === '/') return true;
  if (!pathname.startsWith(cookiePath)) return false;
  return cookiePath.endsWith('/') || pathname.length === cookiePath.length || pathname[cookiePath.length] === '/';
}

export const isExpired = (cookie: Pick<Cookie, 'expires'>, now = Date.now() / 1000): boolean =>
  cookie.expires !== 0 && cookie.expires < now;

function matchesSelector(selector: CookieSelector, cookie: SourcedCookie): boolean {
  if (cookie.profileId !== selector.profileId) return false;
  if (!domainCovers(selector.domain, cookie.domain)) return false;
  return selector.names.length === 0 || selector.names.includes(cookie.name);
}

export interface ResolvedBundle {
  cookies: SourcedCookie[];
  /** Selectors that matched nothing, e.g. after a logout or profile rename. */
  emptySelectors: CookieSelector[];
  /** Profiles that could not be read (locked keychain, missing disk access). */
  errors: Array<{ profileId: string; error: string }>;
}

/**
 * Reads the bundle's cookies live from the browsers. Nothing is cached, so a
 * bundle always reflects the current login state and re-authenticating in the
 * browser is enough to "refresh" an agent's access.
 */
export function resolveBundle(bundle: Bundle, opts: { includeExpired?: boolean } = {}): ResolvedBundle {
  const profileIds = [...new Set(bundle.selectors.map((s) => s.profileId))];
  const reads = readAllProfiles(profileIds);
  const available = reads.flatMap((read) => read.cookies);
  const seen = new Set<string>();
  const cookies: SourcedCookie[] = [];
  const emptySelectors: CookieSelector[] = [];

  for (const selector of bundle.selectors) {
    const matched = available.filter((cookie) => matchesSelector(selector, cookie));
    if (matched.length === 0) emptySelectors.push(selector);
    for (const cookie of matched) {
      if (!opts.includeExpired && isExpired(cookie)) continue;
      const key = `${cookie.profileId}|${cookie.domain}|${cookie.path}|${cookie.name}`;
      if (seen.has(key)) continue;
      seen.add(key);
      cookies.push(cookie);
    }
  }

  return {
    cookies,
    emptySelectors,
    errors: reads.filter((r) => r.error).map((r) => ({ profileId: r.profile.id, error: r.error! })),
  };
}

/** `curl -b` / yt-dlp / requests compatible cookie jar. */
export function toNetscape(cookies: Cookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by cookiejar. Treat this file as a password.', ''];
  for (const cookie of cookies) {
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const prefix = cookie.httpOnly ? '#HttpOnly_' : '';
    lines.push(
      [
        `${prefix}${cookie.domain}`,
        includeSubdomains,
        cookie.path || '/',
        cookie.secure ? 'TRUE' : 'FALSE',
        String(cookie.expires),
        cookie.name,
        cookie.value,
      ].join('\t'),
    );
  }
  return `${lines.join('\n')}\n`;
}

/** Playwright / Puppeteer `storageState` shape. */
export function toStorageState(cookies: Cookie[]): string {
  return JSON.stringify(
    {
      cookies: cookies.map((cookie) => ({
        name: cookie.name,
        value: cookie.value,
        domain: cookie.domain,
        path: cookie.path || '/',
        expires: cookie.expires === 0 ? -1 : cookie.expires,
        httpOnly: cookie.httpOnly,
        secure: cookie.secure,
        sameSite: cookie.sameSite === 'Unspecified' ? 'Lax' : cookie.sameSite,
      })),
      origins: [],
    },
    null,
    2,
  );
}

export function cookieHeaderFor(cookies: Cookie[], url: string): string {
  const target = new URL(url);
  const https = target.protocol === 'https:';
  const applicable = cookies
    .filter((cookie) => cookieAppliesToHost(cookie, target.hostname))
    .filter((cookie) => cookieAppliesToPath(cookie, target.pathname))
    .filter((cookie) => (cookie.secure ? https : true))
    .filter((cookie) => !isExpired(cookie));
  // A bundle can hold the same cookie name from two browsers; a request may only
  // carry one, so the first (longest path wins, as browsers do) is used.
  const byName = new Map<string, Cookie>();
  for (const cookie of [...applicable].sort((a, b) => (b.path || '/').length - (a.path || '/').length)) {
    if (!byName.has(cookie.name)) byName.set(cookie.name, cookie);
  }
  return [...byName.values()].map((cookie) => `${cookie.name}=${cookie.value}`).join('; ');
}
